{% set version = "1.6.5" %}

package:
  name: awesome-slugify
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/awesome-slugify/awesome-slugify-{{ version }}.tar.gz
  sha256: bbdec3fa2187917473a2efad092b57f7125a55f841a7cf6a1773178d32ccfd71
  patches:
    - utf8.patch  # [win]

build:
  number: 6
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - regex
    - unidecode >=1.1.1,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - slugify

about:
  home: https://github.com/dimka665/awesome-slugify
  license: GPL-3.0
  license_family: GPL
  # https://github.com/dimka665/awesome-slugify/issues/24
  # license_file: No license file!
  summary: Python flexible slugify function
  dev_url: https://github.com/dimka665/awesome-slugify
  doc_url: https://github.com/dimka665/awesome-slugify

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
